### ISSUE TITLE
1.21.1报错

### ISSUE THREAD

**Issue by TheQingFengX** [ankhorg/NeigeItems-Kotlin#20]
核心purpur-1.21.1
加载时报错，能正常使用插件

```
[12:58:06 WARN]: [NeigeItems] error occurred while get Class pers.neige.neigeitems.listener.EntityShootBowListener
[12:58:06 WARN]: java.lang.ExceptionInInitializerError
[12:58:06 WARN]:        at java.base/java.lang.Class.forName0(Native Method)
[12:58:06 WARN]:        at java.base/java.lang.Class.forName(Class.java:534)
[12:58:06 WARN]:        at java.base/java.lang.Class.forName(Class.java:513)
[12:58:06 WARN]:        at io.papermc.reflectionrewriter.runtime.AbstractDefaultRulesReflectionProxy.forName(AbstractDefaultRulesReflectionProxy.java:68)
[12:58:06 WARN]:        at io.papermc.paper.pluginremap.reflect.PaperReflectionHolder.forName(Unknown Source)
[12:58:06 WARN]:        at NeigeItems-1.19.19.jar//pers.neige.neigeitems.scanner.ClassScanner.loadClasses(ClassScanner.kt:250)
[12:58:06 WARN]:        at NeigeItems-1.19.19.jar//pers.neige.neigeitems.scanner.ClassScanner.scan(ClassScanner.kt:74)
[12:58:06 WARN]:        at NeigeItems-1.19.19.jar//pers.neige.neigeitems.scanner.ClassScanner.<init>(ClassScanner.kt:65)
[12:58:06 WARN]:        at NeigeItems-1.19.19.jar//pers.neige.neigeitems.NeigeItems.onInit(NeigeItems.java:118)
[12:58:06 WARN]:        at NeigeItems-1.19.19.jar//pers.neige.neigeitems.NeigeItems.<init>(NeigeItems.java:62)
[12:58:06 WARN]:        at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
[12:58:06 WARN]:        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
[12:58:06 WARN]:        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
[12:58:06 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:100)
[12:58:06 WARN]:        at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:125)
[12:58:06 WARN]:        at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:35)
[12:58:06 WARN]:        at io.papermc.paper.plugin.entrypoint.strategy.modern.ModernPluginLoadingStrategy.loadProviders(ModernPluginLoadingStrategy.java:116)
[12:58:06 WARN]:        at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:38)
[12:58:06 WARN]:        at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:40)
[12:58:06 WARN]:        at org.bukkit.craftbukkit.CraftServer.loadPlugins(CraftServer.java:560)
[12:58:06 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:329)
[12:58:06 WARN]:        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1230)
[12:58:06 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:333)
[12:58:06 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)
[12:58:06 WARN]: Caused by: org.bukkit.plugin.IllegalPluginAccessException: Plugin attempted to register class org.bukkit.event.entity.EntityShootBowEvent while not enabled
[12:58:06 WARN]:        at io.papermc.paper.plugin.manager.PaperEventManager.registerEvent(PaperEventManager.java:95)
[12:58:06 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.registerEvent(PaperPluginManagerImpl.java:146)
[12:58:06 WARN]:        at org.bukkit.plugin.SimplePluginManager.registerEvent(SimplePluginManager.java:721)
[12:58:06 WARN]:        at NeigeItems-1.19.19.jar//pers.neige.neigeitems.utils.ListenerUtils.registerListener(ListenerUtils.java:132)
[12:58:06 WARN]:        at NeigeItems-1.19.19.jar//pers.neige.neigeitems.utils.ListenerUtils.registerListener(ListenerUtils.java:69)
[12:58:06 WARN]:        at NeigeItems-1.19.19.jar//pers.neige.neigeitems.listener.EntityShootBowListener.<clinit>(EntityShootBowListener.kt:39)
[12:58:06 WARN]:        ... 24 more
```

**Comment by Neige7** [comment]
1.19.20修了
