### ISSUE TITLE
在最新的purpur1.20.1开服时会一直刷以下报错

### ISSUE THREAD

**Issue by DreamMiu** [ankhorg/NeigeItems-Kotlin#9]
purpur：1.20.1

[12:02:22 WARN]: [NeigeItems] Plugin NeigeItems v1.15.1 generated an exception while executing task 223
org.openjdk.nashorn.internal.runtime.ECMAException: TypeError: Cannot read property "itemDespawnRate" from undefined
        at org.openjdk.nashorn.internal.runtime.ECMAErrors.error(ECMAErrors.java:57) ~[NeigeItems-1.15.1.jar:?]
        at org.openjdk.nashorn.internal.runtime.ECMAErrors.typeError(ECMAErrors.java:212) ~[NeigeItems-1.15.1.jar:?]
        at org.openjdk.nashorn.internal.runtime.ECMAErrors.typeError(ECMAErrors.java:184) ~[NeigeItems-1.15.1.jar:?]
        at org.openjdk.nashorn.internal.runtime.ECMAErrors.typeError(ECMAErrors.java:171) ~[NeigeItems-1.15.1.jar:?]
        at org.openjdk.nashorn.internal.runtime.Undefined.get(Undefined.java:161) ~[NeigeItems-1.15.1.jar:?]
        at org.openjdk.nashorn.internal.scripts.Script$Recompilation$57$10410A$\^eval\_.initNMS#getDespawnRate-4(<eval>:349) ~[?:?]
        at org.openjdk.nashorn.internal.scripts.Script$Recompilation$38$11127AZ$\^eval\_.loadItem(<eval>:395) ~[?:?]
        at org.openjdk.nashorn.internal.scripts.Script$Recompilation$37$3967A$\^eval\_.task#L:114#L:116#L:120(<eval>:121) ~[?:?]
        at org.openjdk.nashorn.javaadapters.java_util_function_Consumer.accept(Unknown Source) ~[?:?]
        at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
        at org.openjdk.nashorn.internal.scripts.Script$Recompilation$29$3734A$\^eval\_.task#L:114#L:116(<eval>:120) ~[?:?]
        at org.openjdk.nashorn.javaadapters.java_util_function_Consumer.accept(Unknown Source) ~[?:?]
        at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
        at org.openjdk.nashorn.internal.scripts.Script$Recompilation$28$3638$\^eval\_.task#L:114(<eval>:116) ~[?:?]
        at org.openjdk.nashorn.javaadapters.java_lang_Runnable.run(Unknown Source) ~[?:?]
        at pers.neige.neigeitems.script.tool.ScriptTask$register$bukkitRunnable$1.run(ScriptTask.kt:78) ~[NeigeItems-1.15.1.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.20.1.jar:git-Purpur-2023]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[purpur-1.20.1.jar:git-Purpur-2023]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[purpur-1.20.1.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by Neige7** [comment]
你这不是NeigeItems的报错，是NeigeItemTag的报错，更新NeigeItemTag的版本
